# Generated by Django 3.2.7 on 2021-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
