# Generated by Django 3.2.7 on 2021-09-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_operations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
    ]
