# Generated by Django 3.2.7 on 2021-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
