# Generated by Django 3.2.7 on 2021-09-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bankaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
