# Generated by Django 3.2.7 on 2021-09-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_operations_operation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('sender', 'receiver')},
        ),
    ]
