# Generated by Django 3.2.7 on 2022-12-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_operation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
